[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps =
    bblanchat/ArduinoJson@^6.21.5
    adafruit/Adafruit HX711@^1.0.0
    milesburton/DallasTemperature@^3.15.0
